### ISSUE TITLE
User-defined classes are applied first

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Component#20]
User-defined classes are applied first, which means they are usually overriden by component classes.
They should be applied last.
Code:
```html
<BlazorStyled.Styled @bind-Classname="@AppBarStyle">
    z-index: calc(var(--theme-zindex-drawer, 1200) + 1);
</BlazorStyled.Styled>

<AppBar class="@AppBarStyle" Position="@AppBarPosition.Fixed">
...
</AppBar>
```
![classes-first](https://user-images.githubusercontent.com/5548662/79043246-6aaf3b80-7bfe-11ea-8d6d-7351e5c45596.PNG)

Also you can notice that AppBar classes are applied twice - but that is not what this issue is about.

**Comment by skclusive** [comment]
this is due to the order of `<style />` docs in the document than order of classes in the dom. (use classes are added at the end).

but this issue is due to our Skclusive-UI's Styling design. that we are not generating bundled style sheet of all the components. instead we want to treat style for component also component which can be rendered statically once (at Router level). with this custom styling also assumed to be used as Style components rendered after Skclusive styles.

ex:
DashboardResources.razor (Skclusive styles via LayoutResources and custom app specific styles)

```html

<ThemeProvider />
<LayoutResources />

<DashboardScripts />
<DashboardStyles />
```

https://github.com/skclusive/Skclusive.Blazor.Samples/blob/master/Skclusive.Blazor.Dashboard/Dashboard.App.View/Resource/DashboardResources.razor

And it is used in Router.razor as below:

```html
<DashboardResources />

<Router
    AppAssembly="@typeof(FullLayout).Assembly">
//...
</Router>
```
https://github.com/skclusive/Skclusive.Blazor.Samples/blob/master/Skclusive.Blazor.Dashboard/Dashboard.App.View/DashboardView.razor

But i guess `BlazorStyled.Styled` renders (or moves the rendered content) the component in head of the document. where as Skclusive-UI styles are rendered inside `<body><app /></body>` hence gets the priority than styles rendered in head.

so need to try out alternatives to get along with `BlazorStyled.Styled`. could you share your thoughts/suggestions on this topic?

**Comment by skclusive** [comment]
Head parameter can be specified to ThemeProvider which would move the style (component styles combined) to the head tag.

```html
<ThemeProvider
    Head>
    <RouterLayout
        Main="@typeof(FullLayout)"
        Mini="@typeof(SmallLayout)" />
</ThemeProvider>
```

using the above feature, BlazorStyled could be used along with Skclusive-UI.

![Screenshot 2020-08-31 at 3 16 01 AM](https://user-images.githubusercontent.com/41325494/91670143-554c9680-eb38-11ea-80fc-3304bd44fc1d.png)

![Screenshot 2020-08-31 at 3 09 50 AM](https://user-images.githubusercontent.com/41325494/91670086-c475bb00-eb37-11ea-80c1-812180080fd9.png)

BlazorStyled seems add styles right be head instead of appending. so i needed a workaround as below in index.html

``html
   <head>
    <meta charset="utf-8" />
    <base href="/" />
    <style data-blazorstyled-name="0" data-blazorstyled-priority="0"></style>
 </head>
```

**Comment by skclusive** [comment]
implemented in develop. closing the issue.
