### ISSUE TITLE
Menu item component

### ISSUE THREAD

**Issue by peteryulius** [skclusive/Skclusive.Material.Component#23]
The menu item when open, seem like delay. It's seem open twice. And the first menu item is gone.

**Comment by esso23** [comment]
Please provide your code and steps how to reproduce the issue.

**Comment by skclusive** [comment]
i guess this is reproducible in server rendering. it is the same menu initially rendered at default location and moved to actually location using jsintro due to network delay it initial rendering might be visible. i noticed (after deployed to azure) same issue in Drawer also.

need to either combine the js-introp or keep the style hidden for initial rendering of the menu and make it visible only when moved to target location.

**Comment by peteryulius** [comment]
> Please provide some code and steps how to reproduce the issue.

Sorry for my slow response,. I just trying in the document. The code such as in the document.

**Comment by peteryulius** [comment]
> i guess this is reproducible in server rendering. it is the same menu initially rendered at default location and moved to actually location using jsintro due to network delay it initial rendering might be visible. i noticed (after deployed to azure) same issue in Drawer also.
> 
> need to either combine the js-introp or keep the style hidden for initial rendering of the menu and make it visible only when moved to target location.

Thank you for the explanation.
