### ISSUE TITLE
Input parameters and Result code from Modal Dialog

### ISSUE THREAD

**Issue by win32nipuh** [skclusive/Skclusive.Material.Component#8]
As for me it may be useful to have possibility to pass parameters and receive Result from a modal dialogs, for example: 
I'd like to ask user "Would you really like to delete the record?" and to receive what user selected.

Something like here
https://github.com/Blazored/Modal

**Comment by skclusive** [comment]
Skclusive-UI Dialog component is used declaratively. the imperative approach in Blazored/Modal will not be supported.

You can achieve the expected behaviour using <Dialog />. you can check the sample here and Dialog documentation. 

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Dialog/Segments/SimpleDialog/SimpleDialogDemo.razor

**Comment by win32nipuh** [comment]
ok, 
please take a look at this closed issue
https://github.com/skclusive/Skclusive.Material.Docs/issues/3

**Comment by skclusive** [comment]
sure. thanks.

**Comment by skclusive** [comment]
closing it. we can reopen if required.
